<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Call to action design</title>
</head>

<body>

    <div class="cta">
        <div class="cta-row">
            <div class="city">تهران</div>
            <div class="phones">
                <div class="phone">۰۲۱-۴۴۰۷۲۸۰۲</div>
                <div class="phone">۰۲۱-۴۴۰۳۳۶۷۷</div>
            </div>
        </div>

        <div class="cta-row">
            <div class="city">کرج</div>
            <div class="phones">
                <div class="phone">۰۲6-۳۴۲۱۴۴۴۱</div>
                <div class="phone">۰۲6-۳۴۲۱۴۴۴۰</div>
            </div>
        </div>
    </div>

</body>

</html>